theme: jekyll-theme-minimal
title: R. Tyler McLaughlin, PhD
description: Postdoctoral fellow at AbbVie biopharma, innovating at the interface of molecular systems biology, genomics, and machine learning.
linkedin: https://www.linkedin.com/in/r-tyler-mclaughlin-phd
github_username: TylerMcLaughlin



markdown: kramdown